/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type CreateUserDto = {
  /**
   * имя пользователя
   *
   * @example lykovrs
   * @minimum 2
   * @maximum 30
   */
  username: string;
  /**
   * информация о пользователе
   *
   * @example About lykovrs.
   * @minimum 2
   * @maximum 200
   * @default Пока ничего не рассказал о себе
   */
  about?: string;
  /**
   * ссылка на аватар
   *
   * @example https://i.pravatar.cc/300
   * @default https://i.pravatar.cc/300
   */
  avatar?: string;
  /**
   * адрес электронной почты пользователя
   *
   * @example lykovrs@gmail.com
   */
  email: string;
  /**
   * пароль пользователя
   *
   * @example strong_password1Aa
   */
  password: string;
};

export type User = {
  /**
   * Уникальный идентификатор
   *
   * @example 1
   */
  id: number;
  /**
   * дата создания, тип значения Date
   *
   * @format date-time
   * @example "2024-08-14T14:46:45.863Z"
   */
  createdAt: string;
  /**
   * дата изменения, тип значения Date
   *
   * @format date-time
   * @example "2024-08-14T14:46:45.864Z"
   */
  updatedAt: string;
  /**
   * имя пользователя
   *
   * @example lykovrs
   * @minimum 2
   * @maximum 30
   */
  username: string;
  /**
   * информация о пользователе
   *
   * @example About lykovrs.
   * @minimum 2
   * @maximum 200
   * @default Пока ничего не рассказал о себе
   */
  about?: string;
  /**
   * ссылка на аватар
   *
   * @example https://i.pravatar.cc/300
   * @default https://i.pravatar.cc/300
   */
  avatar?: string;
  /**
   * адрес электронной почты пользователя
   *
   * @example lykovrs@gmail.com
   */
  email: string;
};

export type UpdateUserDto = {
  /**
   * имя пользователя
   *
   * @example lykovrs
   * @minimum 2
   * @maximum 30
   */
  username?: string;
  /**
   * информация о пользователе
   *
   * @example About lykovrs.
   * @minimum 2
   * @maximum 200
   * @default Пока ничего не рассказал о себе
   */
  about?: string;
  /**
   * ссылка на аватар
   *
   * @example https://i.pravatar.cc/300
   * @default https://i.pravatar.cc/300
   */
  avatar?: string;
  /**
   * адрес электронной почты пользователя
   *
   * @example lykovrs@gmail.com
   */
  email?: string;
  /**
   * пароль пользователя
   *
   * @example strong_password1Aa
   */
  password?: string;
};

export type Wish = {
  /**
   * Уникальный идентификатор
   *
   * @example 1
   */
  id: number;
  /**
   * дата создания, тип значения Date
   *
   * @format date-time
   * @example "2024-08-14T14:46:45.863Z"
   */
  createdAt: string;
  /**
   * дата изменения, тип значения Date
   *
   * @format date-time
   * @example "2024-08-14T14:46:45.864Z"
   */
  updatedAt: string;
};

export type FindUserDto = {
  /**
   * адрес электронной почты или имя пользователя
   *
   * @minimum 1
   * @maximum 150
   */
  query: string;
};

export type CreateWishDto = {};

export type UpdateWishDto = {};

export type CreateWishlistDto = {};

export type UpdateWishlistDto = {};

export type CreateOfferDto = {};
