// This file is auto-generated by @hey-api/openapi-ts

export const $CreateUserDto = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'имя пользователя',
            example: 'lykovrs',
            minimum: 2,
            maximum: 30
        },
        about: {
            type: 'string',
            description: 'информация о пользователе',
            example: 'About lykovrs.',
            minimum: 2,
            maximum: 200,
            default: 'Пока ничего не рассказал о себе'
        },
        avatar: {
            type: 'string',
            description: 'ссылка на аватар',
            example: 'https://i.pravatar.cc/300',
            default: 'https://i.pravatar.cc/300'
        },
        email: {
            type: 'string',
            description: 'адрес электронной почты пользователя',
            example: 'lykovrs@gmail.com'
        },
        password: {
            type: 'string',
            description: 'пароль пользователя',
            example: 'strong_password1Aa'
        }
    },
    required: ['username', 'email', 'password']
} as const;

export const $User = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            description: 'Уникальный идентификатор',
            example: '1'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: 'дата создания, тип значения Date',
            example: '2024-08-28T13:18:00.174Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            description: 'дата изменения, тип значения Date',
            example: '2024-08-28T13:18:00.174Z'
        },
        username: {
            type: 'string',
            description: 'имя пользователя',
            example: 'lykovrs',
            minimum: 2,
            maximum: 30
        },
        about: {
            type: 'string',
            description: 'информация о пользователе',
            example: 'About lykovrs.',
            minimum: 2,
            maximum: 200,
            default: 'Пока ничего не рассказал о себе'
        },
        avatar: {
            type: 'string',
            description: 'ссылка на аватар',
            example: 'https://i.pravatar.cc/300',
            default: 'https://i.pravatar.cc/300'
        },
        email: {
            type: 'string',
            description: 'адрес электронной почты пользователя',
            example: 'lykovrs@gmail.com'
        }
    },
    required: ['id', 'createdAt', 'updatedAt', 'username', 'email']
} as const;

export const $UpdateUserDto = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'имя пользователя',
            example: 'lykovrs',
            minimum: 2,
            maximum: 30
        },
        about: {
            type: 'string',
            description: 'информация о пользователе',
            example: 'About lykovrs.',
            minimum: 2,
            maximum: 200,
            default: 'Пока ничего не рассказал о себе'
        },
        avatar: {
            type: 'string',
            description: 'ссылка на аватар',
            example: 'https://i.pravatar.cc/300',
            default: 'https://i.pravatar.cc/300'
        },
        email: {
            type: 'string',
            description: 'адрес электронной почты пользователя',
            example: 'lykovrs@gmail.com'
        },
        password: {
            type: 'string',
            description: 'пароль пользователя',
            example: 'strong_password1Aa'
        }
    }
} as const;

export const $Wish = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            description: 'Уникальный идентификатор',
            example: '1'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: 'дата создания, тип значения Date',
            example: '2024-08-28T13:18:00.174Z'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            description: 'дата изменения, тип значения Date',
            example: '2024-08-28T13:18:00.174Z'
        }
    },
    required: ['id', 'createdAt', 'updatedAt']
} as const;

export const $FindUserDto = {
    type: 'object',
    properties: {
        query: {
            type: 'string',
            description: 'адрес электронной почты или имя пользователя',
            minimum: 1,
            maximum: 150
        }
    },
    required: ['query']
} as const;

export const $CreateWishDto = {
    type: 'object',
    properties: {}
} as const;

export const $UpdateWishDto = {
    type: 'object',
    properties: {}
} as const;

export const $CreateWishlistDto = {
    type: 'object',
    properties: {}
} as const;

export const $UpdateWishlistDto = {
    type: 'object',
    properties: {}
} as const;

export const $CreateOfferDto = {
    type: 'object',
    properties: {}
} as const;

export const $CreateAchievementDto = {
    type: 'object',
    properties: {}
} as const;

export const $UpdateAchievementDto = {
    type: 'object',
    properties: {}
} as const;