// This file is auto-generated by @hey-api/openapi-ts

export type CreateUserDto = {
    /**
     * имя пользователя
     */
    username: string;
    /**
     * информация о пользователе
     */
    about?: string;
    /**
     * ссылка на аватар
     */
    avatar?: string;
    /**
     * адрес электронной почты пользователя
     */
    email: string;
    /**
     * пароль пользователя
     */
    password: string;
};

export type User = {
    /**
     * Уникальный идентификатор
     */
    id: number;
    /**
     * дата создания, тип значения Date
     */
    createdAt: string;
    /**
     * дата изменения, тип значения Date
     */
    updatedAt: string;
    /**
     * имя пользователя
     */
    username: string;
    /**
     * информация о пользователе
     */
    about?: string;
    /**
     * ссылка на аватар
     */
    avatar?: string;
    /**
     * адрес электронной почты пользователя
     */
    email: string;
};

export type UpdateUserDto = {
    /**
     * имя пользователя
     */
    username?: string;
    /**
     * информация о пользователе
     */
    about?: string;
    /**
     * ссылка на аватар
     */
    avatar?: string;
    /**
     * адрес электронной почты пользователя
     */
    email?: string;
    /**
     * пароль пользователя
     */
    password?: string;
};

export type Wish = {
    /**
     * Уникальный идентификатор
     */
    id: number;
    /**
     * дата создания, тип значения Date
     */
    createdAt: string;
    /**
     * дата изменения, тип значения Date
     */
    updatedAt: string;
};

export type FindUserDto = {
    /**
     * адрес электронной почты или имя пользователя
     */
    query: string;
};

export type CreateWishDto = {
    [key: string]: unknown;
};

export type UpdateWishDto = {
    [key: string]: unknown;
};

export type CreateWishlistDto = {
    [key: string]: unknown;
};

export type UpdateWishlistDto = {
    [key: string]: unknown;
};

export type CreateOfferDto = {
    [key: string]: unknown;
};

export type CreateAchievementDto = {
    [key: string]: unknown;
};

export type UpdateAchievementDto = {
    [key: string]: unknown;
};

export type AuthControllerSignUpData = {
    requestBody: CreateUserDto;
};

export type AuthControllerSignUpResponse = User;

export type AuthControllerSigninData = {
    requestBody: unknown;
};

export type AuthControllerSigninResponse = unknown;

export type UsersControllerMeResponse = User;

export type UsersControllerUpdateMeData = {
    requestBody: UpdateUserDto;
};

export type UsersControllerUpdateMeResponse = User;

export type UsersControllerGetMyWishesResponse = Array<Wish>;

export type UsersControllerFindOneByNameData = {
    name: string;
};

export type UsersControllerFindOneByNameResponse = User;

export type UsersControllerFindWishesByNameData = {
    name: string;
};

export type UsersControllerFindWishesByNameResponse = Array<Wish>;

export type UsersControllerFindData = {
    requestBody: FindUserDto;
};

export type UsersControllerFindResponse = User;

export type WishesControllerCreateData = {
    requestBody: CreateWishDto;
};

export type WishesControllerCreateResponse = unknown;

export type WishesControllerFindLastResponse = unknown;

export type WishesControllerFindTopResponse = unknown;

export type WishesControllerFindOneData = {
    id: string;
};

export type WishesControllerFindOneResponse = unknown;

export type WishesControllerUpdateData = {
    id: string;
    requestBody: UpdateWishDto;
};

export type WishesControllerUpdateResponse = unknown;

export type WishesControllerRemoveData = {
    id: string;
};

export type WishesControllerRemoveResponse = unknown;

export type WishesControllerCopyData = {
    id: string;
};

export type WishesControllerCopyResponse = unknown;

export type WishlistsControllerCreateData = {
    requestBody: CreateWishlistDto;
};

export type WishlistsControllerCreateResponse = unknown;

export type WishlistsControllerFindAllResponse = unknown;

export type WishlistsControllerFindOneData = {
    id: string;
};

export type WishlistsControllerFindOneResponse = unknown;

export type WishlistsControllerUpdateData = {
    id: string;
    requestBody: UpdateWishlistDto;
};

export type WishlistsControllerUpdateResponse = unknown;

export type WishlistsControllerRemoveData = {
    id: string;
};

export type WishlistsControllerRemoveResponse = unknown;

export type OffersControllerCreateData = {
    requestBody: CreateOfferDto;
};

export type OffersControllerCreateResponse = unknown;

export type OffersControllerFindAllResponse = unknown;

export type OffersControllerFindOneData = {
    id: string;
};

export type OffersControllerFindOneResponse = unknown;

export type AchievementsControllerCreateData = {
    requestBody: CreateAchievementDto;
};

export type AchievementsControllerCreateResponse = unknown;

export type AchievementsControllerFindLastResponse = unknown;

export type AchievementsControllerFindOneData = {
    id: string;
};

export type AchievementsControllerFindOneResponse = unknown;

export type AchievementsControllerUpdateData = {
    id: string;
    requestBody: UpdateAchievementDto;
};

export type AchievementsControllerUpdateResponse = unknown;

export type AchievementsControllerRemoveData = {
    id: string;
};

export type AchievementsControllerRemoveResponse = unknown;

export type AchievementsControllerCopyData = {
    id: string;
};

export type AchievementsControllerCopyResponse = unknown;

export type $OpenApiTs = {
    '/signup': {
        post: {
            req: AuthControllerSignUpData;
            res: {
                /**
                 * Пользователь успешно создан.
                 */
                200: User;
            };
        };
    };
    '/signin': {
        post: {
            req: AuthControllerSigninData;
            res: {
                /**
                 * Успешная авторизация.
                 */
                200: unknown;
            };
        };
    };
    '/users/me': {
        get: {
            res: {
                /**
                 * Пользователь
                 */
                200: User;
            };
        };
        patch: {
            req: UsersControllerUpdateMeData;
            res: {
                /**
                 * Пользователь
                 */
                200: User;
            };
        };
    };
    '/users/me/wishes': {
        get: {
            res: {
                /**
                 * Мои подарки
                 */
                200: Array<Wish>;
            };
        };
    };
    '/users/{name}': {
        get: {
            req: UsersControllerFindOneByNameData;
            res: {
                /**
                 * Пользователь
                 */
                200: User;
            };
        };
    };
    '/users/{name}/wishes': {
        get: {
            req: UsersControllerFindWishesByNameData;
            res: {
                /**
                 * Подарки пользователя
                 */
                200: Array<Wish>;
            };
        };
    };
    '/users/find': {
        post: {
            req: UsersControllerFindData;
            res: {
                /**
                 * Пользователь
                 */
                200: User;
            };
        };
    };
    '/wishes': {
        post: {
            req: WishesControllerCreateData;
            res: {
                201: unknown;
            };
        };
    };
    '/wishes/last': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/wishes/top': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/wishes/{id}': {
        get: {
            req: WishesControllerFindOneData;
            res: {
                200: unknown;
            };
        };
        patch: {
            req: WishesControllerUpdateData;
            res: {
                200: unknown;
            };
        };
        delete: {
            req: WishesControllerRemoveData;
            res: {
                200: unknown;
            };
        };
    };
    '/wishes/{id}/copy': {
        post: {
            req: WishesControllerCopyData;
            res: {
                201: unknown;
            };
        };
    };
    '/wishlistlists': {
        post: {
            req: WishlistsControllerCreateData;
            res: {
                201: unknown;
            };
        };
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/wishlistlists/{id}': {
        get: {
            req: WishlistsControllerFindOneData;
            res: {
                200: unknown;
            };
        };
        patch: {
            req: WishlistsControllerUpdateData;
            res: {
                200: unknown;
            };
        };
        delete: {
            req: WishlistsControllerRemoveData;
            res: {
                200: unknown;
            };
        };
    };
    '/offers': {
        post: {
            req: OffersControllerCreateData;
            res: {
                201: unknown;
            };
        };
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/offers/{id}': {
        get: {
            req: OffersControllerFindOneData;
            res: {
                200: unknown;
            };
        };
    };
    '/achievement': {
        post: {
            req: AchievementsControllerCreateData;
            res: {
                201: unknown;
            };
        };
    };
    '/achievement/last': {
        get: {
            res: {
                200: unknown;
            };
        };
    };
    '/achievement/{id}': {
        get: {
            req: AchievementsControllerFindOneData;
            res: {
                200: unknown;
            };
        };
        patch: {
            req: AchievementsControllerUpdateData;
            res: {
                200: unknown;
            };
        };
        delete: {
            req: AchievementsControllerRemoveData;
            res: {
                200: unknown;
            };
        };
    };
    '/achievement/{id}/copy': {
        post: {
            req: AchievementsControllerCopyData;
            res: {
                201: unknown;
            };
        };
    };
};